### ISSUE TITLE
Support for connecting to Hosts with passwords?

### ISSUE THREAD

**Issue by nathvi** [nlunn/serilog-sinks-redis#1]
How do you connect to a host with a password? This is not covered in the usage.

**Comment by nathvi** [comment]
????

**Comment by Refresh06** [comment]
Hi Nathvi,

We have developed the sink for our purposes at our workplace and has chosen to share if anybody needed it.

As we do not have password protection of our Redis installation we will not be implementing it any time soon.

You are welcome to make a Pull request if you implement the changes needed.

Regards
